# Docker Compose for Vinted Koopjes with Tailscale
version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vinted_db
      POSTGRES_USER: vinted
      POSTGRES_PASSWORD: vintedpass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: gunicorn vinted_koopjes.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://vinted:vintedpass123@db:5432/vinted_db
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db
    networks:
      - app-network

  tasks:
    build: .
    command: python manage.py process_tasks
    volumes:
      - .:/code
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://vinted:vintedpass123@db:5432/vinted_db
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db
      - web
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge