# Generated by Django 5.2.5 on 2025-08-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('search_parameters', models.JSONField()),
                ('std_dev_threshold', models.FloatField(default=1.5)),
                ('absolute_price_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Price Watch',
                'verbose_name_plural': 'Price Watches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VintedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinted_id', models.IntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.IntegerField()),
                ('api_response', models.JSONField()),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-first_seen'],
                'indexes': [models.Index(fields=['condition', 'price'], name='watches_vin_conditi_98c3ef_idx'), models.Index(fields=['vinted_id'], name='watches_vin_vinted__c92456_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.IntegerField()),
                ('mean_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('std_deviation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.IntegerField()),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('price_watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watches.pricewatch')),
            ],
            options={
                'verbose_name': 'Price Statistics',
                'verbose_name_plural': 'Price Statistics',
                'unique_together': {('price_watch', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='UnderpriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('price_difference', models.DecimalField(decimal_places=2, max_digits=10)),
                ('std_deviations_below', models.FloatField()),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('price_watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watches.pricewatch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watches.vinteditem')),
            ],
            options={
                'verbose_name': 'Underprice Alert',
                'verbose_name_plural': 'Underprice Alerts',
                'ordering': ['-detected_at'],
                'unique_together': {('price_watch', 'item')},
            },
        ),
    ]
