# Generated by Django 5.2.5 on 2025-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricewatch',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='watches', to='watches.vinteditem'),
        ),
    ]
