# Generated by Django 5.2.5 on 2025-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_pricewatch_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinteditem',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vinteditem',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vinteditem',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
