# Generated by Django 5.2.5 on 2025-08-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_vinteditem_brand_vinteditem_size_vinteditem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinteditem',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vinteditem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
