# Generated by Django 5.2.5 on 2025-08-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0004_vinteditem_color_vinteditem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricewatch',
            name='blacklist_words',
            field=models.TextField(blank=True, help_text='Comma-separated words to exclude items from calculations. Items containing these words in title/description will be ignored.'),
        ),
    ]
