# Generated by Django 5.2.5 on 2025-08-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0005_pricewatch_blacklist_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinteditem',
            name='upload_date',
            field=models.DateTimeField(blank=True, help_text='When the item was uploaded to Vinted (from API timestamp)', null=True),
        ),
    ]
