# Generated by Django 5.2.5 on 2025-08-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0006_vinteditem_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricewatch',
            name='highlight_words',
            field=models.TextField(blank=True, help_text='Comma-separated words to highlight items with thick double border. Items containing these words in title/description will be visually highlighted.'),
        ),
    ]
