# Generated by Django 5.2.5 on 2025-08-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0007_add_highlight_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='underpricealert',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide this alert from display'),
        ),
    ]
