# Generated by Django 5.2.5 on 2025-08-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0008_add_hidden_to_alerts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='underpricealert',
            index=models.Index(fields=['price_watch', 'hidden'], name='watches_und_price_w_9c3325_idx'),
        ),
        migrations.AddIndex(
            model_name='underpricealert',
            index=models.Index(fields=['detected_at'], name='watches_und_detecte_268175_idx'),
        ),
        migrations.AddIndex(
            model_name='underpricealert',
            index=models.Index(fields=['hidden'], name='watches_und_hidden_4fae7d_idx'),
        ),
        migrations.AddIndex(
            model_name='underpricealert',
            index=models.Index(fields=['email_sent'], name='watches_und_email_s_3cab8f_idx'),
        ),
        migrations.AddIndex(
            model_name='vinteditem',
            index=models.Index(fields=['upload_date'], name='watches_vin_upload__e1c341_idx'),
        ),
        migrations.AddIndex(
            model_name='vinteditem',
            index=models.Index(fields=['first_seen'], name='watches_vin_first_s_8d459a_idx'),
        ),
        migrations.AddIndex(
            model_name='vinteditem',
            index=models.Index(fields=['last_seen'], name='watches_vin_last_se_07af19_idx'),
        ),
        migrations.AddIndex(
            model_name='vinteditem',
            index=models.Index(fields=['is_active'], name='watches_vin_is_acti_5d9759_idx'),
        ),
        migrations.AddIndex(
            model_name='vinteditem',
            index=models.Index(fields=['condition', 'upload_date'], name='watches_vin_conditi_a6251f_idx'),
        ),
        migrations.AddIndex(
            model_name='vinteditem',
            index=models.Index(fields=['price', 'upload_date'], name='watches_vin_price_ea0902_idx'),
        ),
    ]
