# Generated by Django 5.2.5 on 2025-08-19 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0009_add_database_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.IntegerField()),
                ('date', models.DateField()),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watches.pricewatch')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['price_watch', 'date'], name='watches_pri_price_w_e7b910_idx'), models.Index(fields=['date'], name='watches_pri_date_1c27e4_idx'), models.Index(fields=['condition', 'date'], name='watches_pri_conditi_3dcb63_idx')],
                'unique_together': {('price_watch', 'condition', 'date')},
            },
        ),
    ]
