# Generated by Django 5.2.5 on 2025-08-20 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0010_pricetrend'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('monitor', 'Monitor Price Watches'), ('check_watch', 'Check Individual Watch'), ('cleanup', 'Cleanup Old Items'), ('token_refresh', 'Token Refresh'), ('manual_index', 'Manual Index All')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=10)),
                ('items_processed', models.IntegerField(default=0, help_text='Number of items processed')),
                ('pages_fetched', models.IntegerField(default=0, help_text='Number of pages fetched from API')),
                ('new_items_found', models.IntegerField(default=0, help_text='Number of new items discovered')),
                ('alerts_generated', models.IntegerField(default=0, help_text='Number of new alerts generated')),
                ('error_message', models.TextField(blank=True, help_text='Error details if task failed')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Task duration in seconds', null=True)),
                ('price_watch', models.ForeignKey(blank=True, help_text='Related watch (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='watches.pricewatch')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_type', '-started_at'], name='watches_scr_task_ty_211921_idx'), models.Index(fields=['status', '-started_at'], name='watches_scr_status_b3ce35_idx'), models.Index(fields=['price_watch', '-started_at'], name='watches_scr_price_w_fcea04_idx')],
            },
        ),
    ]
