# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0011_scrapeactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VintedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('session', 'Session Token')], max_length=10, unique=True)),
                ('value', models.TextField(help_text='The actual token value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this token was used', null=True)),
                ('is_valid', models.BooleanField(default=True, help_text='False if token has failed and needs replacement')),
                ('error_count', models.IntegerField(default=0, help_text='Number of consecutive API errors with this token')),
                ('last_error', models.TextField(blank=True, help_text='Last error message encountered with this token')),
                ('last_error_at', models.DateTimeField(blank=True, help_text='When the last error occurred', null=True)),
            ],
            options={
                'ordering': ['token_type'],
            },
        ),
        migrations.AddIndex(
            model_name='vintedtoken',
            index=models.Index(fields=['token_type', 'is_valid'], name='watches_vin_token_t_b5b89e_idx'),
        ),
    ]