# Generated by Django 5.2.5 on 2025-08-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0012_vintedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinteditem',
            name='seller_business',
            field=models.BooleanField(default=False, help_text='Whether seller is a business account'),
        ),
        migrations.AddField(
            model_name='vinteditem',
            name='seller_id',
            field=models.IntegerField(blank=True, help_text='Vinted user ID of the seller', null=True),
        ),
        migrations.AddField(
            model_name='vinteditem',
            name='seller_login',
            field=models.CharField(blank=True, help_text="Seller's username/login", max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='vinteditem',
            index=models.Index(fields=['seller_id'], name='watches_vin_seller__3bda1d_idx'),
        ),
        migrations.AddIndex(
            model_name='vinteditem',
            index=models.Index(fields=['seller_login'], name='watches_vin_seller__d97193_idx'),
        ),
    ]
