# Generated by Django 5.2.5 on 2025-08-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0013_add_seller_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinteditem',
            name='favourite_count',
            field=models.IntegerField(blank=True, help_text='Number of users who favorited this item', null=True),
        ),
        migrations.AddField(
            model_name='vinteditem',
            name='service_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Vinted's service fee for this item", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vinteditem',
            name='total_item_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price including fees', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vinteditem',
            name='view_count',
            field=models.IntegerField(blank=True, help_text='Number of times this item was viewed', null=True),
        ),
    ]
