# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0014_add_api_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vintedtoken',
            name='never_expire',
            field=models.BooleanField(default=False, help_text='If true, token will never expire automatically (only when rejected by Vinted)'),
        ),
    ]