# Generated by Django 5.2.5 on 2025-08-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0015_add_never_expire_to_tokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VintedToken',
        ),
    ]
