# Generated by Django 5.2.5 on 2025-08-25 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0016_remove_vinted_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.IntegerField(help_text='Total items analyzed')),
                ('total_clusters', models.IntegerField(help_text='Number of clusters found')),
                ('noise_items', models.IntegerField(help_text="Items that didn't cluster")),
                ('eps_parameter', models.FloatField(default=0.5, help_text='DBSCAN eps parameter')),
                ('min_samples', models.IntegerField(default=5, help_text='DBSCAN min_samples parameter')),
                ('execution_time', models.FloatField(help_text='Execution time in seconds')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watches.pricewatch')),
            ],
            options={
                'verbose_name': 'Cluster Analysis',
                'verbose_name_plural': 'Cluster Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(help_text='Cluster ID (-1 for noise/outliers)')),
                ('distance_to_centroid', models.FloatField(help_text='Distance from cluster centroid')),
                ('is_representative', models.BooleanField(default=False, help_text='Is this item representative of the cluster')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watches.clusteranalysis')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watches.vinteditem')),
                ('price_watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watches.pricewatch')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_embedding', models.JSONField(help_text='Title text embedding as list')),
                ('description_embedding', models.JSONField(help_text='Description text embedding as list')),
                ('image_embedding', models.JSONField(help_text='Image embedding as list')),
                ('embedding_version', models.CharField(help_text='Track model versions', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='watches.vinteditem')),
            ],
        ),
        migrations.AddIndex(
            model_name='clusteranalysis',
            index=models.Index(fields=['price_watch', '-created_at'], name='watches_clu_price_w_124275_idx'),
        ),
        migrations.AddIndex(
            model_name='clusteranalysis',
            index=models.Index(fields=['status', '-created_at'], name='watches_clu_status_a5c62b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcluster',
            index=models.Index(fields=['price_watch', 'cluster_id'], name='watches_ite_price_w_1968b1_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcluster',
            index=models.Index(fields=['cluster_analysis', 'cluster_id'], name='watches_ite_cluster_9c9169_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcluster',
            index=models.Index(fields=['cluster_id', 'is_representative'], name='watches_ite_cluster_33a06e_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcluster',
            index=models.Index(fields=['distance_to_centroid'], name='watches_ite_distanc_ddd5e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcluster',
            unique_together={('cluster_analysis', 'item')},
        ),
        migrations.AddIndex(
            model_name='itemembedding',
            index=models.Index(fields=['created_at'], name='watches_ite_created_1b2a07_idx'),
        ),
        migrations.AddIndex(
            model_name='itemembedding',
            index=models.Index(fields=['embedding_version'], name='watches_ite_embeddi_a5223e_idx'),
        ),
    ]
