# Generated by Django 5.2.5 on 2025-08-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0017_clusteranalysis_itemcluster_itemembedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False, help_text='Is the API currently blocked?')),
                ('blocked_since', models.DateTimeField(blank=True, help_text='When blocking started', null=True)),
                ('last_blocked_check', models.DateTimeField(auto_now=True, help_text='Last time we checked blocking status')),
                ('last_successful_request', models.DateTimeField(blank=True, help_text='Last successful API call', null=True)),
                ('consecutive_failures', models.IntegerField(default=0, help_text='Number of consecutive API failures')),
                ('test_watch_id', models.IntegerField(blank=True, help_text='ID of watch to use for testing during blocked state', null=True)),
            ],
            options={
                'verbose_name': 'API Blocking State',
                'verbose_name_plural': 'API Blocking States',
            },
        ),
    ]
